import { describe, it, expect } from "vitest";
import { hashTypedData, verifyTypedData } from "viem";
import { buildAttestationTypedData } from "./attestations";
import fixture from "../fixtures/eip712-fixture.json";

const fx = fixture as {
  chainId: string;
  verifyingContract: `0x${string}`;
  diveId: string;
  nonce: string;
  digest: `0x${string}`;
  attester: `0x${string}`;
  v: number;
  r: `0x${string}`;
  s: `0x${string}`;
};

/**
 * Cross-consistency with the Solidity reference implementation: the fixture is
 * generated by forge (deployment/script/EmitEip712Fixture.s.sol) using
 * DiveLogTypedData.attestationDigest + vm.sign. If the TS side (domain, type
 * string, field order) ever drifts from the contract, these fail.
 */
describe("EIP-712 TS <-> Solidity cross-check", () => {
  const typedData = buildAttestationTypedData(
    Number(fx.chainId),
    fx.verifyingContract,
    BigInt(fx.diveId),
    BigInt(fx.nonce),
  );

  it("produces the same digest as DiveLogTypedData.attestationDigest", () => {
    expect(hashTypedData(typedData as never)).toBe(fx.digest);
  });

  it("the forge signature recovers to the expected attester", async () => {
    const signature =
      (fx.r + fx.s.slice(2) + fx.v.toString(16).padStart(2, "0")) as `0x${string}`;
    await expect(
      verifyTypedData({ ...typedData, address: fx.attester, signature } as never),
    ).resolves.toBe(true);
  });

  it("documents the malleability guard: the (flipped-v, n−s) twin is what the contract rejects", async () => {
    // secp256k1n / 2 — the contract's EIP-2 bound (SovereignDiveLog._HALF_N)
    const halfN = BigInt("0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0");
    const n = BigInt("0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141");
    const sLow = BigInt(fx.s);
    const sHigh = n - sLow;
    const vFlipped = fx.v === 27 ? 28 : 27;
    const malleated =
      (fx.r +
        ("0x" + sHigh.toString(16).padStart(64, "0")).slice(2) +
        vFlipped.toString(16).padStart(2, "0")) as `0x${string}`;

    // Raw ECDSA recovery accepts the twin (same address) — that's malleability.
    await expect(
      verifyTypedData({ ...typedData, address: fx.attester, signature: malleated } as never),
    ).resolves.toBe(true);
    // The reference implementation closes the hole by rejecting s > n/2:
    expect(sLow <= halfN).toBe(true); // canonical form passes the contract
    expect(sHigh > halfN).toBe(true); // malleable twin reverts InvalidSignature
  });
});
